kirppu/urls.py
from django.conf.urls import patterns, url
from django.conf import settings

from .views import (
    get_clerk_codes,
    get_counter_commands,
    get_barcode,
    checkout_view,
    overseer_view,
    vendor_view,
    get_items,
    all_to_print,
    item_add,
    item_hide,
    item_to_printed,
    item_to_not_printed,
    item_update_name,
    item_update_type,
    item_update_price,
    remove_item_from_receipt,
    login_view,
    logout_view,
    stats_view,
)
from .checkout_api import AJAX_FUNCTIONS, checkout_js

__author__ = 'jyrkila'

_urls = [
    url(r'^clerks/$', get_clerk_codes, name='clerks'),
    url(r'^commands/$', get_counter_commands),
    url(r'^barcode/(?P<data>\w+?)\.(?P<ext>\w+)$', get_barcode, name='barcode'),
    url(r'^checkout/$', checkout_view, name='checkout_view'),
    url(r'^overseer/$', overseer_view, name='overseer_view'),
    url(r'^stats/$', stats_view, name='stats_view'),
    url(r'^vendor/$', vendor_view, name='vendor_view'),
    url(r'^vendor/items/$', get_items, name='page'),
    url(r'^vendor/items/move_to_print$', all_to_print, name='all_to_print'),
    url(r'^vendor/item/$', item_add, name='item_add'),
    url(r'^vendor/item/(?P<code>\w+?)/to_printed$', item_to_printed, name='item_to_printed'),
    url(r'^vendor/item/(?P<code>\w+?)/price$', item_update_price, name='item_update_price'),
    url(r'^vendor/item/(?P<code>\w+?)/name$', item_update_name, name='item_update_name'),
    url(r'^vendor/item/(?P<code>\w+?)/type$', item_update_type, name='item_update_type'),
    url(r'^vendor/item/(?P<code>\w+?)/to_not_printed$', item_to_not_printed, name='item_to_not_printed'),
    url(r'^vendor/item/(?P<code>\w+?)/hide$', item_hide, name='item_hide'),
    url(r'^remove_item', remove_item_from_receipt, name='remove_item_from_receipt'),
]

if settings.KIRPPU_USE_SSO:
    _urls.append(url(r'^login/?$', login_view, name='login_view'))
    _urls.append(url(r'^logout/?$', logout_view, name='logout_view'))


if settings.KIRPPU_CHECKOUT_ACTIVE:  # Only activate API when checkout is active.
    _urls.append(url('^api/checkout.js$', checkout_js, name='checkout_js'))
    _urls.extend([
        url(func.url, "kirppu.checkout_api.%s" % func.name, name=func.view_name)
        for func in AJAX_FUNCTIONS.itervalues()
    ])

urlpatterns = patterns('', *_urls)

kirppu_project/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'packages': ('kirppu',),
}

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'kirppu.views.index', name='home'),
    url(r'^kirppu/', include('kirppu.urls', app_name="kirppu", namespace="kirppu")),
    url(r'^auth/', include('kirppuauth.urls', app_name="kirppuauth", namespace="kirppuauth")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
)

kirppu/views.py
from collections import namedtuple
from decimal import Decimal, InvalidOperation
import decimal
import json
from django.core.exceptions import PermissionDenied
from .checkout_api import clerk_logout_fn
from . import ajax_util
from .forms import ItemRemoveForm
from kirppu.util import get_form
import re
import urllib

import barcode

from django.http.response import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseForbidden, HttpResponseRedirect)
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.conf import settings
import django.core.urlresolvers as url
from django.utils.http import is_safe_url
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_http_methods
from django.contrib.auth import logout, get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext as _

from .models import (
    Item,
    Clerk,
    Vendor,
)
from .utils import require_setting, PixelWriter, require_vendor_open, is_vendor_open, barcode_view, \
    require_test
from templatetags.kirppu_tags import get_dataurl, KirppuBarcode


def index(request):
    return redirect("kirppu:vendor_view")


@login_required
@require_http_methods(["POST"])
@require_vendor_open
def item_add(request):
    vendor = Vendor.get_vendor(request.user)
    name = request.POST.get("name", u"").strip()
    price = request.POST.get("price", "")
    tag_type = request.POST.get("type", "short")
    suffix_str = request.POST.get("range", u"")
    itemtype = request.POST.get("itemtype", u"")
    adult = request.POST.get("adult", "no")

    if not itemtype:
        return HttpResponseBadRequest(_(u"Item must have a type."))

    if not price:
        return HttpResponseBadRequest(_(u"Item must have a price."))

    price = price.replace(",", ".")
    try:
        price = Decimal(price).quantize(Decimal('0.1'), rounding=decimal.ROUND_UP)
    except InvalidOperation:
        return HttpResponseBadRequest(_(u"Price must be numeric."))

    # Round up to nearest 50 cents.
    remainder = price % Decimal('.5')
    if remainder > Decimal('0'):
        price += Decimal('.5') - remainder

    if price <= Decimal('0'):
        return HttpResponseBadRequest(_(u"Price too low. (min 0.5 euros)"))
    elif price > Decimal('400'):
        return HttpResponseBadRequest(_(u"Price too high. (max 400 euros)"))

    def expand_suffixes(input_str):
        """Turn 'a b 1 3-4' to ['a', 'b', '1', '3', '4']"""
        words = input_str.split()
        result = []

        for word in words:
            # Handle the range syntax as a special case.
            match = re.match(r"(\d+)-(\d+)$", word)
            if match:
                # Turn '1-3' to ['1', '2', '3'] and so on
                left, right = map(int, match.groups())
                if abs(left - right) + 1 > 100:
                    return None
                if left > right:
                    left, right = right, left
                result.extend(map(unicode, range(left, right + 1)))
            else:
                result.append(word)

        return result

    suffixes = expand_suffixes(suffix_str)
    if suffixes is None:
        return HttpResponseBadRequest(_(u'Maximum of 100 items allowed by a single range statement.'))

    if not suffixes:
        # If there are no suffixes the name is added as is just once.
        # This is equivalent to adding empty string as suffix.
        suffixes.append(u"")

    item_cnt = Item.objects.filter(vendor=vendor).count()

    # Create the items and construct a response containing all the items that have been added.
    response = []
    max_items = settings.KIRPPU_MAX_ITEMS_PER_VENDOR
    for suffix in suffixes:
        if item_cnt >= max_items:
            error_msg = _(u"You have %(max_items)s items, which is the maximum. No more items can be registered.")
            return HttpResponseBadRequest(error_msg % {'max_items': max_items})
        item_cnt += 1

        suffixed_name = (name + u" " + suffix).strip()
        item = Item.new(name=suffixed_name, price=str(price), vendor=vendor, type=tag_type, state=Item.ADVERTISED, itemtype=itemtype, adult=adult)
        item_dict = {
            'vendor_id': vendor.id,
            'code': item.code,
            'barcode_dataurl': get_dataurl(item.code, 'png'),
            'name': item.name,
            'price': str(item.price_fmt).replace('.', ','),
            'type': item.type,
            'adult': item.adult
        }
        response.append(item_dict)

    return HttpResponse(json.dumps(response), 'application/json')


@login_required
@require_http_methods(["POST"])
def item_hide(request, code):
    vendor = Vendor.get_vendor(request.user)
    item = get_object_or_404(Item.objects, code=code, vendor=vendor)

    item.hidden = True
    item.save()

    return HttpResponse()


@login_required
@require_http_methods(['POST'])
def item_to_not_printed(request, code):
    vendor = Vendor.get_vendor(request.user)
    item = get_object_or_404(Item.objects, code=code, vendor=vendor)

    if settings.KIRPPU_COPY_ITEM_WHEN_UNPRINTED:
        # Create a duplicate of the item with a new code and hide the old item.
        # This way, even if the user forgets to attach the new tags, the old
        # printed tag is still in the system.
        if not is_vendor_open():
            return HttpResponseForbidden("Registration is closed")

        new_item = Item.new(name=item.name, price=item.price,
                vendor=item.vendor, type=item.type, state=Item.ADVERTISED, itemtype=item.itemtype, adult=item.adult)
        item.hidden = True
    else:
        item.printed = False
        new_item = item
    item.save()

    item_dict = {
        'vendor_id': new_item.vendor_id,
        'code': new_item.code,
        'barcode_dataurl': get_dataurl(item.code, 'png'),
        'name': new_item.name,
        'price': str(new_item.price).replace('.', ','),
        'type': new_item.type,
        'adult': new_item.adult,
    }

    return HttpResponse(json.dumps(item_dict), 'application/json')


@login_required
@require_http_methods(["POST"])
def item_to_printed(request, code):
    vendor = Vendor.get_vendor(request.user)
    item = get_object_or_404(Item.objects, code=code, vendor=vendor)

    item.printed = True
    item.save()

    return HttpResponse()


@login_required
@require_http_methods(["POST"])
@require_vendor_open
def item_update_price(request, code):
    price = request.POST.get("value", "0")
    if len(price) > 8:
        return HttpResponseBadRequest("Invalid price.")
    price = price.replace(",", ".")

    price = Decimal(price).quantize(Decimal('.1'), rounding=decimal.ROUND_UP)

    # Round up to nearest 50 cents.
    remainder = price % Decimal('.5')
    if remainder > Decimal('0'):
        price += Decimal('.5') - remainder

    if price <= Decimal('0'):
        return HttpResponseBadRequest("Price too low.")
    elif price > Decimal('400'):
        return HttpResponseBadRequest("Price too high.")

    vendor = Vendor.get_vendor(request.user)
    item = get_object_or_404(Item.objects, code=code, vendor=vendor)

    if item.is_locked():
        return HttpResponseBadRequest("Item has been brought to event. Price can't be changed.")

    item.price = str(price)
    item.save()

    return HttpResponse(str(price).replace(".", ","))


@login_required
@require_http_methods(["POST"])
@require_vendor_open
def item_update_name(request, code):
    name = request.POST.get("value", "no name")
    
    name = name[:80]

    vendor = Vendor.get_vendor(request.user)
    item = get_object_or_404(Item.objects, code=code, vendor=vendor)

    if item.is_locked():
        return HttpResponseBadRequest("Item has been brought to event. Name can't be changed.")

    item.name = name
    item.save()

    return HttpResponse(name)


@login_required
@require_http_methods(["POST"])
def item_update_type(request, code):
    tag_type = request.POST.get("tag_type", None)

    vendor = Vendor.get_vendor(request.user)
    item = get_object_or_404(Item.objects, code=code, vendor=vendor)
    item.type = tag_type
    item.save()
    return HttpResponse()


@login_required
@require_http_methods(["POST"])
def all_to_print(request):
    vendor = Vendor.get_vendor(request.user)
    items = Item.objects.filter(vendor=vendor).filter(printed=False)

    items.update(printed=True)

    return HttpResponse()


def _vendor_menu_contents(request):
    """
    Generate menu for Vendor views.
    Returned tuple contains entries for the menu, each entry containing a
    name, url, and flag indicating whether the entry is currently active
    or not.

    :param request: Current request being processed.
    :return: List of menu items containing name, url and active fields.
    :rtype: tuple[MenuItem,...]
    """
    active = request.resolver_match.view_name
    menu_item = namedtuple("MenuItem", "name url active")
    fill = lambda name, func: menu_item(name, url.reverse(func), func == active)

    return (
        fill(_(u"Home"), "kirppu:vendor_view"),
        fill(_(u"Item list"), "kirppu:page"),
    )


@login_required
@require_http_methods(["GET"])
@barcode_view
def get_items(request, bar_type):
    """
    Get a page containing all items for vendor.

    :param request: HttpRequest object.
    :type request: django.http.request.HttpRequest
    :return: HttpResponse or HttpResponseBadRequest
    """

    user = request.user
    if user.is_staff and "user" in request.GET:
        user = get_object_or_404(get_user_model(), username=request.GET["user"])
    tag_type = request.GET.get("tag", "short").lower()
    if tag_type not in ('short', 'long'):
        return HttpResponseBadRequest(u"Tag type not supported")

    vendor = Vendor.get_vendor(user)
    vendor_items = Item.objects.filter(vendor=vendor, hidden=False)
    items = vendor_items.filter(printed=False)
    printed_items = vendor_items.filter(printed=True)

kirppu/templates/kirppu/app_checkout.html
{% extends "kirppu/common.html" %}{% load i18n %}

{% load static %}

{% block title %}Kirppu - Checkout{% endblock %}

{% block head %}
    <link href="{% static "kirppu/css/general.css" %}" rel="stylesheet">
    <link href="{% static "kirppu/css/checkout.css" %}" rel="stylesheet">
    <script src="{% static "kirppu/js/general.js" %}"></script>
    <script src="{% static "kirppu/js/checkout.js" %}"></script>
    <script src="{% static "kirppu/js/checkout_comp.js" %}"></script>
{% endblock %}

{% block navbar_left %}
    <li class="dropdown" id="modeMenu"><a href="javascript:void(1)" class="dropdown-toggle" data-toggle="dropdown">Counter mode <b class="caret"></b></a>
        <ul class="dropdown-menu">
        <li>
            <a href="javascript:void(1)" data-entrypoint="customer_checkout" class="color-CounterMode"><span class="glyphicon glyphicon-euro"></span> Checkout counter</a>
        </li>
        <li>
            <a href="javascript:void(1)" data-entrypoint="vendor_check_in" class="color-ItemCheckInMode"><span class="glyphicon glyphicon-import"></span> Vendor Check-In</a>
        </li>
        <li>
            <a href="javascript:void(1)" data-entrypoint="reports" class="color-ReceiptPrintMode"><span class="glyphicon glyphicon-list-alt"></span> Receipt Search</a>
        </li>
        <li>
            <a href="javascript:void(1)" data-entrypoint="vendor_check_out" class="color-VendorCheckoutMode"><span class="glyphicon glyphicon-export"></span> Vendor Check-Out</a>
        </li>
        <li>
            <a href="javascript:void(1)" data-entrypoint="vendor_find" class="color-VendorFindMode"><span class="glyphicon glyphicon-user"></span> Vendor Search</a>
        </li>
        </ul>
    </li>
{% endblock %}
{% block navbar_right %}
    <li><a href="{% url 'kirppu:stats_view' %}" title="Stats">Stats</a></li>
    <li id="overseer_link" class="hidden">
        <a href="{% url 'kirppu:overseer_view' %}" title="Overseer Dashboard">Overseer Dashboard</a>
    </li>
    <li>
        <button type="button" class="btn navbar-btn btn-link" data-toggle="modal" data-target="#help_dialog"><span class="glyphicon glyphicon-question-sign"></span> Help</button>
    </li>
{% endblock %}

{% block body %}
    <h1>
        <span id="mode_glyph" class="glyphicon glyphicon-euro"></span>
        <span id="title_text">Checkout</span>
        <small id="subtitle_text" class="hidden-print"></small>
    </h1>
    <div class="alert alert-danger alert-off" role="alert" id="error_container"></div>
    <div class="alert alert-warning alert-off" role="alert" id="warning_container"></div>
    <form role="form" id="code_form" class="hidden-print">
        <div class="form-group">
            <label class="sr-only" for="code_input">Code</label>
            <input type="text" id="code_input" class="form-control"
                   placeholder="Barcode" autofocus="true"/>
        </div>
    </form>

    <div id="receipt_body"></div>
{% endblock  %}

{% block tail %}
<script type="application/javascript"
        src="{% url 'kirppu:checkout_js' %}"
        charset="UTF-8"></script>
<script type="application/javascript"><!--
    CheckoutConfig.uiId.container = "body";
    CheckoutConfig.uiId.body = "receipt_body";
    CheckoutConfig.uiId.errorText = "error_container";
    CheckoutConfig.uiId.warningText = "warning_container";
    CheckoutConfig.uiId.glyph = "mode_glyph";
    CheckoutConfig.uiId.stateText = "title_text";
    CheckoutConfig.uiId.subtitleText = "subtitle_text";
    CheckoutConfig.uiId.codeInput = "code_input";
    CheckoutConfig.uiId.codeForm = "code_form";
    CheckoutConfig.uiId.modeMenu = "modeMenu";
    CheckoutConfig.uiId.overseerLink= "overseer_link";
    CheckoutConfig.uiId.dialog = "dialog_template";
    DateTimeFormatter.locales = "{{ LANGUAGE_CODE }}";
    DateTimeFormatter.timeZone = "{{ TIME_ZONE }}";
    DateTimeFormatter.init();

{# Until js localization domain is splitted from the public domain, using this. #}
{% language settings.LANGUAGE_CODE %}
    ReceiptPrintMode.strTotal = "{% trans "Total:" %}";
    PrintReceiptTable.strVendor = "{% trans "vendor" %}";
    PrintReceiptTable.strCode = "{% trans "code" %}";
    PrintReceiptTable.strItem = "{% trans "name" %}";
    PrintReceiptTable.strPrice = "{% trans "price" %}";
{% endlanguage %}

    $(document).ready(function() {
        setupAjax();
        CheckoutConfig.check();
        new ModeSwitcher().startDefault();
    });
//--></script>
    <div class="modal fade" id="help_dialog" tabindex="-1" role="dialog" aria-labelledby="help_dialog_label"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="help_dialog_label">Counter Help</h4>
                </div>
                <div class="modal-body">
                    <table class="table table-condensed">
                        <thead>
                        <tr>
                            <th>Action</th>
                            <th>Input</th>
                            <th>Example</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Log out from counter</td>
                            <td><kbd data-command-value="logout"></kbd></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Abort current receipt</td>
                            <td><kbd data-command-value="abort"></kbd></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Remove item from receipt</td>
                            <td><kbd>-ITEM_CODE</kbd></td>
                            <td><code>-PF72NOZI</code></td>
                        </tr>
                        <tr>
                            <td>Payment</td>
                            <td><kbd>+EUROS,CENTS</kbd></td>
                            <td><code>+12,00</code> for 12,00&euro;</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="dialog_template" tabindex="-1" role="dialog" aria-labelledby="dialog_template_label"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span
                            aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="dialog_template_label">&lt;Dialog&gt;</h4>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

kirppu/templates/kirppu/app_item_receipt_remove.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Remove item from receipt</title>
</head>
<body>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit"/></p>
</form>
</body>
</html>

kirppu/templates/kirppu/app_items.html
{% extends "kirppu/app_vendor.html" %}{% load kirppu_tags %}{% load i18n %}

{% load static %}

{% block head %}

    <link href="{% static "kirppu/css/general.css" %}" rel="stylesheet">
    <link href="{% static "kirppu/css/price_tags.css" %}" rel="stylesheet">
    <script src="{% static "kirppu/js/general.js" %}"></script>
    <script src="{% static "kirppu/js/jeditable.js" %}"></script>
    <script src="{% static "kirppu/js/price_tags.js" %}"></script>
{% endblock %}

{% block body %}
    {% if is_registration_open %}
    <form id="item-add-form" method="POST" class="form-horizontal">
        {% csrf_token %}
        <p class="help-block">
            {% load_text "item_info1" %}
        </p>
        <p class="help-block">
            {% load_text "item_info2" %}
        </p>
        <p class="help-block">
            {% load_text "item_info3" %}
        </p>
        <p class="help-block">
            {% load_text "item_info4" %}
            <a href="">{% trans "price tag guide" %}</a>
        </p>
        <p class="help-block">
            {% blocktrans %}After you have printed your price tags, you should mark them as
            having already been printed with the 'Mark all as printed' button. Doing so moves them
            to the bottom of the page and they are no longer printed when you print the page.{% endblocktrans %}
        </p>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{% trans "Add new item" %}</h3>
            </div>
            <div class="panel-body">

        <div class="form-group">
            <label for="item-add-name" class="col-sm-1 control-label">{% trans "Name:" %}</label>
            <div class="col-sm-6">
                <input id="item-add-name" type="text" class="form-control" placeholder="{% trans "Ranma ½ Vol." %}" />
            </div>

            <label for="item-add-suffixes" class="col-sm-1 control-label">{% trans "Suffixes:" %}</label>
            <div class="col-sm-4 ">
                <input id="item-add-suffixes" type="text" class="form-control" placeholder="{% trans "1 3-5  A B  Blue" %}" />
            </div>
        </div>
        <div class="form-group">
            <label for="item-add-price" class="col-sm-1 control-label">{% trans "Price:" %}</label>
            <div class="col-sm-2">
                <input id="item-add-price" type="text" class="form-control" placeholder="5" />
            </div>
            <label class="control-label">&euro;</label>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label">{% trans "Size:" %}</label>
            <div class="col-sm-11">
                <label class="radio-inline">
                    <input name="item-add-type" value="tiny" type="radio" />{% trans "Tiny" %}
                </label>
                <label class="radio-inline">
                    <input name="item-add-type" value="short" type="radio" checked="checked" />{% trans "Short" %}
                </label>
                <label class="radio-inline">
                    <input name="item-add-type" value="long" type="radio" />{% trans "Long" %}
                </label>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-1 control-label">{% trans "Type:" %}</label>
            <div class="col-sm-6">
                <select id="item-add-itemtype" name="item-add-itemtype" class="form-control">
                    <option></option>
                    <option value="manga-finnish">{% trans "Manga (Finnish)" %}</option>
                    <option value="manga-english">{% trans "Manga (English)" %}</option>
                    <option value="manga-other">{% trans "Manga (other language)" %}</option>
                    <option value="book">{% trans "Book" %}</option>
                    <option value="magazine">{% trans "Magazine" %}</option>
                    <option value="movie-tv">{% trans "Movie/TV-series" %}</option>
                    <option value="game">{% trans "Game" %}</option>
                    <option value="figurine-plushie">{% trans "Figurine/Plushie" %}</option>
                    <option value="clothing">{% trans "Clothing" %}</option>
                    <option value="other">{% trans "Other" %}</option>
                </select>
            </div>

            <label class="col-sm-1 control-label">{% trans "Adult:" %}</label>
            <div class="col-sm-3">
                <label class="radio-inline">
                    <input name="item-add-adult" value="yes" type="radio" />{% trans "Yes" %}
                </label>
                <label class="radio-inline">
                    <input name="item-add-adult" value="no" type="radio" checked="checked" />{% trans "No" %}
                </label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-1 col-sm-6">
                <div id="form-errors" class="text-danger"></div>
                <button id="add_short_item" type="submit" class="btn btn-primary">{% trans "Add item" %}</button>
            </div>
            <div class="col-sm-5">
                <button id="print_items" type="button" class="btn btn-success">{% trans "Print" %}</button>
            </div>
        </div>
        </div></div>{# panel-body, panel #}
    </form>
    {% endif %}

    <form id="item-add-form" method="POST" class="form-horizontal">
        <div class="form-group">
            <div class="col-sm-12">
                <button id="list_view" type="button" class="btn btn-default">{% trans "Toggle List View" %}</button>
                <button id="delete_all" type="button" class="btn btn-default">{% trans "Mark all as printed" %}</button>
            </div>
        </div>
    </form>

    {# Output a single item_container as a template for javascript. #}
    {% include 'kirppu/app_items_item.html' with tag_type="template" name="" price="0" code="" vendor_id="" adult="" locked=False %}

    <div id="items">
        {# Output a template container for every non-printed item user has. #}
        {% for i in items %}
            {% include 'kirppu/app_items_item.html' with name=i.name price=i.price_fmt code=i.code vendor_id=i.vendor_id tag_type=i.type adult=i.adult locked=i.is_locked %}
        {% endfor %}
    </div>
    <div style="margin-top: 1cm" id="printed_items">
        {# Output a template container for every printed item user has. #}
        {% for i in printed_items %}
            {% include 'kirppu/app_items_item.html' with name=i.name price=i.price_fmt code=i.code vendor_id=i.vendor_id tag_type="list" adult=i.adult locked=True %}
        {% endfor %}
    </div>
{% endblock %}

{% block tail %}
    <script>
        itemsConfig.url_args.code = '__placeholder__';
        itemsConfig.urls.item_add = "{% url 'kirppu:item_add' %}";
        itemsConfig.urls.barcode_img = "{% url 'kirppu:barcode' '__placeholder__' bar_type %}";
        itemsConfig.urls.price_update = "{% url 'kirppu:item_update_price' '__placeholder__' %}";
        itemsConfig.urls.name_update = "{% url 'kirppu:item_update_name' '__placeholder__' %}";
        itemsConfig.urls.item_to_list = "{% url 'kirppu:item_to_printed' '__placeholder__' %}";
        itemsConfig.urls.size_update = "{% url 'kirppu:item_update_type' '__placeholder__' %}";
        itemsConfig.urls.all_to_print = "{% url 'kirppu:all_to_print' %}";
        itemsConfig.urls.roller = "{% static "img/roller.gif" %}";
        itemsConfig.urls.item_to_print = "{% url 'kirppu:item_to_not_printed' '__placeholder__' %}";
        itemsConfig.urls.item_hide = "{% url 'kirppu:item_hide' '__placeholder__' %}";
        {% if not is_registration_open %}itemsConfig.enabled = false;{% endif %}

        $(document).ready(function() {
            setupAjax();

            bindFormEvents();

            bindTagEvents($('#items > .item_editable'));
            bindListTagEvents($('#printed_items > .item_container'));
        });
    </script>
{% endblock %}